language: generic 
sudo: required
services:
  - docker

before install:
  - docker build -t marek/mui-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true marek/mui-practice npm run test

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "eu-north-1"
  app: "mui-practice"
  env: "MuiPractice-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-085471374027" 
  bucket_path: "mui-practice"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
